---
- name: Add mariadb repo
  yum_repository:
    baseurl: http://yum.mariadb.org/10.5/centos7-amd64
    description: MariaDB repo
    file: mariadb
    gpgcheck: yes
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    name: mariadb
- name: Install mariadb
  yum:
      disablerepo: *
      enablerepo: mariadb
      name:
        - MariaDB-server
        - MariaDB-client
      state: present
- name: Start mariadb
  systemd:
    enabled: yes
    name: mariadb
    state: started
