---
- name: Add jenkins repo
  yum_repository:
    baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    description: Jenkins repo
    file: jenkins
    gpgcheck: true
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    name: jenkins

- name: Install jenkins
  dnf:
      name:
        - gcc-c++
        - jenkins
        - make
      state: present
  ansible_python_interpreter: /usr/bin/python

- name: Start jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true
