---
- name: Start docker registry
  docker_container:
      container_default_behavior: compatibility
      env:
        #DOCKER_HOST: "tcp://{{ ansible_hostname }}.local:{{ registry_port }}"
        DOCKER_HOST: "tcp://{{ ansible_hostname }}:{{ registry_port }}"
        DOCKER_TLS_VERIFY: "1"
        REGISTRY_HTTP_TLS_CERTIFICATE: "{{ tls_crt_file }}"
        REGISTRY_HTTP_TLS_KEY: "{{ tls_private_key_file }}"
      image: registry:2
      name: registry
      published_ports: "{{ registry_port }}:5000"
      restart_policy: always
      state: started
      volumes: /etc/pki/tls:/etc/pki/tls
  vars:
    registry_port: 2376
