---
- name: Upgrade pip
  shell: python3 -m pip install --upgrade pip

- name: Verify python OpenSSL existence
  pip:
    executable: pip3
    name: 
      - PyOpenSSL

- name: Verify SSL dir existence
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ssl_dir }}/certs"
    - "{{ ssl_dir }}/csr"
    - "{{ ssl_dir }}/private"

- name: Generate OpenSSL private key
  openssl_privatekey:
    path: "{{ ssl_private_key_file }}"

- name: Generate OpenSSL CSR
  openssl_csr:
    common_name: "{{ inventory_hostname }}.local"
    path: "{{ ssl_csr_file }}"
    privatekey_path: "{{ ssl_private_key_file }}"

- name: Generate self-signed OpenSSL cert
  openssl_certificate:
    csr_path: "{{ ssl_csr_file }}"
    path: "{{ ssl_crt_file }}"
    privatekey_path: "{{ ssl_private_key_file }}"
    provider: selfsigned
