---
- name: Add webmin repo
  yum_repository:
    description: webmin repo
    file: webmin
    gpgcheck: yes
    gpgkey: http://www.webmin.com/jcameron-key.asc
    mirrorlist: http://download.webmin.com/download/yum/mirrorlist
    name: webmin

- name: Install webmin
  dnf:
    name:
      - webmin
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python

- name: Register sudo user password extraction command
  register: cmd_result
  shell: "grep '{{ sudo_user }}' /etc/shadow | awk -F: '{ print $2 }'"

- set_fact:
    sudo_user_hashed_password: "{{ cmd_result.stdout }}"

- name: Add sudo user to webmin users
  template:
    backup: true
    dest: "{{ miniserv_users_file }}"
    src: templates/miniserv.users.j2

- name: Add sudo user to ACL
  lineinfile:
    backup: true
    insertafter: EOF
    line: "{{ sudo_user }}:*"
    path: /etc/webmin/webmin.acl

- name: Start webmin
  sysvinit:
    enabled: true
    name: webmin
    state: started
