---
- name: Update docker daemon
  copy:
    backup: true
    dest: /etc/docker/daemon.json
    src: "{{ docker_daemon_src }}"

- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted

- name: Add kubernetes repo
  yum_repository:
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    description: Kubernetes repo
    file: kubernetes
    gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    name: kubernetes

- name: Install kubernetes
  dnf:
    name:
        - kubelet
        - kubeadm
        - kubectl
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python

- name: Start kubectl
  systemd:
    enabled: yes    
    name: kubelet
    state: started

- name: Initialise kubernetes cluster
  command: "kubeadm init --apiserver-advertise-address={{ api_addr }} --pod-network-cidr={{ pod_cidr }}"

- name: Create .kube dir
  file:
    path: "/home/{{ sudo_user }}/.kube"
    state: directory

- name: Copy config to .kube
  copy:
    dest: "/home/{{ sudo_user }}/.kube/config"
    src: /etc/kubernetes/admin.conf

- name: Change ownership of .kube/config
  file:
    group: "{{ sudo_user }}"
    owner: "{{ sudo_user }}"
    path: "/home/{{ sudo_user }}/.kube/config"

- name: Create pod network
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- delegate_to: localhost
  copy: 
    content: "{{ join_command.stdout_lines[0] }}"
    dest: /tmp/join_command
