---
- name: Download nodejs repo installer
  get_url:
    dest: "{{ node_repo_installer }}"
    url: https://rpm.nodesource.com/setup_10.x
    mode: 0755

- name: Run nodejs repo installer
  command: "{{ node_repo_installer }}"

- name: Install nodejs
  dnf:
    name:
      - nodejs
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python
