---
- name: Initialise kubernetes cluster
  # command: "kubeadm init --apiserver-advertise-address={{ api_addr }} --pod-network-cidr={{ pod_cidr }}"
  command: kubeadm init

- name: Create .kube dir
  file:
    path: "{{ kubeconfig_dir }}"
    state: directory

- name: Copy config to .kube
  copy:
    dest: "{{ kubeconfig }}"
    remote_src: true
    src: /etc/kubernetes/admin.conf

- name: Change ownership of .kube/config
  file:
    group: "{{ sudo_user }}"
    owner: "{{ sudo_user }}"
    path: "{{ kubeconfig }}"

- name: Create pod network
  become: true
  become_user: root
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Enable kubelet
  systemd:
    enabled: true
    name: kubelet

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "{{ join_command_file }}"
  delegate_to: localhost
