---
- name: Install nginx
  dnf:
    name:
      - nginx

- name: Template nginx.conf
  ansible.builtin.template:
      backup: true
      dest: /etc/nginx/nginx.conf
      src: templates/nginx.conf.j2

- name: Start Nginx
  systemd:
    enabled: yes
    name: nginx
    state: started
