---
- hosts: all
  become: true
  roles:
    - hostnamectl
    - avahi
    - hosts

- hosts: controllers
  become: true
  roles:
    - kubernetes-master
    - jenkins-config

- hosts: workers
  become: true
  roles:
    - kubernetes-worker
